name: "Build And Deploy"
on:
  push:
    branches:
      - main
jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Create Build
        run: npm run build
      - name: Uplaod Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: dist-files
          path: dist
